### ISSUE TITLE
Selection of publisher filter sometimes get unset

### ISSUE THREAD

**Issue by bsimyo** [TerriaJS/magda-web#9]
eg search "water", click on top publisher in publisher list. Rather than leaving it in a selected state, it flicks back to it being unselected.  Subsequent selection works.  This seems to be new as I haven't seen it before and am pretty sure I've done the same thing before (though may be wrong). 
(happens on at least latest Chrome)

**Comment by chloeleichen** [comment]
The reason this happens is because in the following query: 
`http://magda-search-api.terria.io/datasets/search?query=water+by%20Department%20of%20Environment,%20Land,%20Water%20&%20Planning&start=0&limit=10`
the publisher name becomes `Department of Environment, Land, Water` when returned to me (it should be `Department of Environment, Land, Water & Planning`, so the UI can't find a match therefore the active options becomes inactive. When clicked the second time, the query didn't change so the UI doesn't make another request therefore it stays active. 

@AlexGilleran Can you have a look why the query parser has lost `& planning` ?

**Comment by AlexGilleran** [comment]
@chloeleichen are you sure? Seems fine now if I do that exact request...

![image](https://cloud.githubusercontent.com/assets/900555/20992597/39185ea8-bd39-11e6-8e75-e5b153d1d151.png)

**Comment by chloeleichen** [comment]
Yes, but it's not in `query`
<img width="560" alt="screen shot 2016-12-08 at 11 28 24 am" src="https://cloud.githubusercontent.com/assets/7508939/20992636/7d7a9d5e-bd39-11e6-9d6d-e9fa6c3c8de9.png">

**Comment by chloeleichen** [comment]
ok I'll escape the &

**Comment by AlexGilleran** [comment]
:)

**Comment by chloeleichen** [comment]
So there was a bug with my input sanitising, should be fixed now
